services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: sportfit-app
    ports:
      - "6868:8080"
    networks:
      - springcloud
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_sportfit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    container_name: sportfit-db
    networks:
      - springcloud
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_sportfit
    ports:
      - "5433:5432"
volumes:
  db_data:
networks:
  springcloud:
    name: springcloud