spring.application.name=crud
spring.datasource.url=jdbc:postgresql://localhost:5432/db_sportfit
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#No envia todo el trace al usuario
server.error.include-stacktrace=never
spring.web.error.include-stacktrace=never
server.error.include-path=never

logging.level.root=INFO
logging.level.com.upc.sportfit=info
logging.file.name=logs/api.log

# CORS Frontend
ip.frontend=http://localhost:4200

# JWT Secret (512-bit base64 encoded)
jwt.secret=0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==

